/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.game;

public class App {
    public static void main(String[] args) {
        GameEngineCotroller gameEngineCotroller = new GameEngineCotroller();
        gameEngineCotroller.run();
    }
}
